### ISSUE TITLE
Add jline3 and expose raw keyboard input somehow

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/mosaic#10]

**Comment by opatry** [comment]
You mean, having `Modifier.onKeyEvent()`, right?
If so, I guess `KeyEvent` would be different from the Android/Desktop one which is in the `ui` package.

**Comment by JakeWharton** [comment]
It's probably not _that_ different in shape, but yes we are not reusing anything from Compose UI / Foundation.

**Comment by EpicDima** [comment]
I think we can use [mordant](https://github.com/ajalt/mordant) to handle the user input that was added in this [pull request](https://github.com/ajalt/mordant/pull/175). It remains only to wait for the official new version to try

**Comment by JakeWharton** [comment]
Yeah just saw that earlier. Cool!

**Comment by JakeWharton** [comment]
This version upgrade just landed.

**Comment by JakeWharton** [comment]
Did most of this today in the `keys` branch. Will try to finish it tonight.

Probably need to restore `MosaicScope` to add an `exitApplication` function similar to what Compose UI for Desktop does. I'm also unsure what to do about <kbd>Ctrl</kbd>+<kbd>C</kbd> handling. It might be worth having automatic handling of that with some kind of opt-out.

**Comment by JakeWharton** [comment]
Also I'm about to unconditionally put the terminal in raw mode. Is there any reason to not do that? I see a few other frameworks unconditionally do it as well.

**Comment by JakeWharton** [comment]
For ctrl+c, if no one handles it in a modifier, we'll exit. Otherwise, you're on your own.
