### ISSUE TITLE
Variable doesn't get rerendered

### ISSUE THREAD

**Issue by kqvanity** [JakeWharton/mosaic#185]
I'm having a project that interacts with an API using okhttp, and the project is recursively sending requests, waiting for them, then return the responses. I had the logic inside a NewConnection class that implements an interface `ConnectionObserver`
I was trying to get the overridden methods to update a variable that gets displayed by mosaic, but unfortunately it doesn't.
Any ideas?

Also the library seem to be really deficit in documentation. The only link referenced is mere API reference! 

```kotlin
suspend fun TUIClient() = runMosaic {
        var result by mutableStateOf("")
        setContent {
                Text ("The count is: ${result}")
        }

        var newConnection: NewConnection = NewConnection(object: ConnectionObserver {

            override fun onConnected() {
                result = "Connected"
            }

            override fun onUserDisconnected() {
                result  = "User disconnected"
            }

            override fun onTyping() {
                result = "Typing"
            }

            override fun onGotMessage(message: String) {
                result = message
            }

            override fun onSomethingElse() {
                /* println("Response is ${response}") */
                result = "Something else happened!"
            }

        })

    // construct a new connection and pass the Connection observer argument
    newConnection.start()
}
```

**Comment by JakeWharton** [comment]
You need to block the runMosaic lambda from returning. When it returns the composition is canceled.

An easy way to do that here is a CompletableDeferred<Unit> that you define and await at the bottom. Then, when the websocket or whatever completes you send Unit to it. I'm on mobile so can't quite type up it exactly.

**Comment by kqvanity** [comment]
Alright thanks!

> An easy way to do that here is a CompletableDeferred 

I'm also open for other solutions.
