### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by sgammon** [JakeWharton/mosaic#208]
Hey @JakeWharton,

Could we respectfully request a release? We're on `1.9.0` now (thank you), but we have to use a custom version of the Compose compiler in order to ship for WASM. That's waiting on #206 which is done but not released.

**Comment by sgammon** [comment]
Obviously this next release should preclude this from ever being an issue again, so thank you on that front as well 🚀

**Comment by JakeWharton** [comment]
I tried to yesterday, in fact, but ran out of time. I'm on vacation this week. Maybe it gets done, but maybe it doesn't. At worst: next week!

For now, you can use Gradle dependency substitution to redirect the coordinates we add with your own.

**Comment by sgammon** [comment]
thanks for the WA 👍🏻 have a great vacation

**Comment by sgammon** [comment]
(i'll keep this open so i remember to drop the substitution, if that's okay)

**Comment by JakeWharton** [comment]
https://github.com/JakeWharton/mosaic/releases/tag/0.9.0

Will still take 15-60m for the bits to show up on Maven Central.

**Comment by JakeWharton** [comment]
Nevermind they're there now! I literally got the popup notification as I hit the "comment" button.

**Comment by sgammon** [comment]
@JakeWharton thank you! works great
