### ISSUE TITLE
Support true color palette

### ISSUE THREAD

**Issue by YohannesTz** [JakeWharton/mosaic#209]
how do I set custom RGB colors to Text composable? or is there a way to get (an extension function probably) the RGB value of the provided colors in the [Color](https://github.com/JakeWharton/mosaic/blob/trunk/mosaic-runtime/src/commonMain/kotlin/com/jakewharton/mosaic/ui/Color.kt) class?

**Comment by YohannesTz** [comment]
oh! turns out there is a list of those. but still open to how to do it

https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux

**Comment by JakeWharton** [comment]
Eventually we'll probably support a full 24bit palette, but for now no there's no way. Leaving this open as a feature request for the true color palette.
