### ISSUE TITLE
Publish to MavenCentral

### ISSUE THREAD

**Issue by Jonas164** [JakeWharton/mosaic#28]
Hello,

I wanted to try out mosaic in my own project. Sadly, it seems like it is not available in the MavenCentral repository. Would it be possible to publish it there?
Having to build the project locally is a major barrier to people simply wanting to try it out :)

**Comment by JakeWharton** [comment]
Blocked on #26. I'm replacing Yoga with ConstraintLayout's core. Right now you build yourself because I don't have a multiplatform JNI setup.

**Comment by Shabinder** [comment]
Can we hope this to happen soon too ?, as #26 is closed resolved... Anyhow NO rush , as experimenting  with it as a submodule works too

**Comment by JakeWharton** [comment]
It will happen when it happens. At the very least I need to write documentation on how to use the tool before a release. It is mostly unblocked, though.

**Comment by JakeWharton** [comment]
Done
