### ISSUE TITLE
Use effects to denote scope of work

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/mosaic#3]
Currently we build our own coroutine scope to encapsulate all of the work required to render. When this scope ends, rendering ends and the program exits cleanly (modulo internal nonsense to make this work).

Ideally effects inside the composition are used to scope the composition instead. Compose internals currently prevent this, which is tracked as https://issuetracker.google.com/issues/169425431.

**Comment by JakeWharton** [comment]
Today:
```kotlin
fun main() = runMosaic {
  val countValue = mutableStateOf(0)

  setContent {
    val count by remember { countValue }
    Text("The count is: $count")
  }

  for (i in 1..20) {
    delay(250)
    countValue.value = i
  }
}
```
Tomorrow:
```kotlin
fun main() = runMosaic {
  val count by remember { mutableStateOf(0) }
  Text("The count is: $count")

  LaunchedEffect(null) {
    for (i in 1..20) {
      delay(250)
      count++
    }
  }
}
```

**Comment by JakeWharton** [comment]
I was doing some Compose UI for Desktop recently, and it seems like they support this internally. Need to investigate.

**Comment by m-sasha** [comment]
I think what you need is something like `FlushCoroutineDispatcher` from Compose Multiplatform.

**Comment by JakeWharton** [comment]
Done in #284
