### ISSUE TITLE
Koltin 1.5.10 & Compose (1.0.0-beta08) Support 

### ISSUE THREAD

**Issue by Shabinder** [JakeWharton/mosaic#30]
I am trying out it in my project and I found it still depends on compose (1.0.0-beta07) , is there any plan to move onto **beta08** ?

**Comment by JakeWharton** [comment]
The project builds both the Compose runtime and compiler from source and therefore does not correspond to a particular release. I have a local branch which moves it somewhere between beta09 and beta10, but it's currently failing and I haven't had time to figure out why.

**Comment by Shabinder** [comment]
> The project builds both the Compose runtime and compiler from source and therefore does not correspond to a particular release. I have a local branch which moves it somewhere between beta09 and beta10, but it's currently failing and I haven't had time to figure out why.

Ohhhk, I will wait then ...

**Comment by ch8n** [comment]
Hi @JakeWharton thanks for the framework, compose new release is there and Kotlin is updated to 1.6.0, can we have a new update? also if we can have a guide to manually upgrade it would be great. You can share some resources then I can create a PR with documentation on that.
