### ISSUE TITLE
Add support for Kotlin 1.9.23

### ISSUE THREAD

**Issue by IsakTheHacker** [JakeWharton/mosaic#328]
Add support for Kotlin 1.9.23 when the next stable Compose Compiler compatible with that version drops

**Comment by JakeWharton** [comment]
1.9.23 support already landed in #326. I was not planning to make a release for it.

For now, you can follow these instructions: https://github.com/JakeWharton/mosaic?tab=readme-ov-file#custom-compose-compiler. The compatible version is 1.5.10.
