### ISSUE TITLE
Support rendering in raw mode

### ISSUE THREAD

**Issue by typfel** [JakeWharton/mosaic#336]
When entering raw mode in a terminal the automatic translation of `\n` into `\r\n` is disabled, this causes the rendering using mosaic to break since it only outputs `\n` during rendering.

See: https://unix.stackexchange.com/questions/366423/unexpected-indentation-behaviour-when-i-set-the-terminal-to-raw-mode-why-is-th

I suppose not all terminal libraries disable this automatic conversion since the robot sample renders correctly using the jline3 library but many do including https://github.com/crossterm-rs/crossterm which I'm building Kotlin bindings for https://github.com/typfel/crossterm-kmp

I've applied this change in https://github.com/typfel/mosaic/tree/fix/use-crlf-newlines and from my testing it seems to work both cases when raw mode is enabled / disabled.

**Comment by JakeWharton** [comment]
Yeah interesting stuff. Just played around with it locally using `stty` and some `echo -e`. I don't see any downside to emitting the full CRLF regardless of what mode you're in.

Do you want to make a PR with your change?

**Comment by typfel** [comment]
I'll open a PR
