### ISSUE TITLE
Status of LaunchedEffect blocker?

### ISSUE THREAD

**Issue by vpuonti** [JakeWharton/mosaic#338]
Hi, 

Just letting you know that the Issuetracker ticket that is linked under section [Why doesn't work take place in a LaunchedEffect?](https://github.com/JakeWharton/mosaic?tab=readme-ov-file#why-doesnt-work-take-place-in-a-launchedeffect) has recently been marked as "Won't fix (Obsolete)". 

That is all, happy Easter!

**Comment by JakeWharton** [comment]
Yeah I got the email 😭 . Only Google could screw up managing an issue tracker so badly.

Our tracking issue is #3, and as noted in there Compose Desktop seems to be doing this today. There's also an open PR trying to integrate it #284.
