### ISSUE TITLE
Migrate to the new JetBrains Compose Gradle + compiler plugin

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/mosaic#340]
https://github.com/JetBrains/kotlin/tree/master/plugins/compose
https://github.com/JetBrains/kotlin/tree/master/libraries/tools/kotlin-compose-compiler

And stop maintaining ours

**Comment by sgammon** [comment]
sorry for the stray tag, just very excited about this and will be adopting it as soon as it hits :D

**Comment by JakeWharton** [comment]
Well check out https://github.com/JakeWharton/mosaic/releases/tag/0.13.0!
