### ISSUE TITLE
 suspend modifier is missing in Readme.md

### ISSUE THREAD

**Issue by gavr123456789** [JakeWharton/mosaic#418]
https://github.com/JakeWharton/mosaic/blob/trunk/README.md?plain=1#L25  

![image](https://github.com/user-attachments/assets/2f9a775f-beef-45de-b4d5-bf343ae3879c)  
  
![image](https://github.com/user-attachments/assets/9403957a-1bf0-4696-87be-aeb0766c1193)

**Comment by JakeWharton** [comment]
The function was renamed to `runMosaicBlocking` and is available on JVM and native. `runMosaic` is suspending and also works on JS.
