### ISSUE TITLE
Real frame time uses 2 times `tv_nsec`

### ISSUE THREAD

**Issue by EdwarDDay** [JakeWharton/mosaic#481]
Maybe I understand something wrong, but in linux and mingw target it looks like the current time gets created by multiplying the nanoseond part with 1000 and adding the nanosecond part again.
https://github.com/JakeWharton/mosaic/blob/c3f36e078377ee4a34ff5fd056eda6b845844138/mosaic-runtime/src/linuxMain/kotlin/com/jakewharton/mosaic/platform.kt#L32
Shouldn't this be 
```kotlin
timespec.tv_sec * 1_000_000L + timespec.tv_nsec
```
?
It's at least used like this in [`kotlinx.datetime`](https://github.com/Kotlin/kotlinx-datetime/blob/30ab530c3ee41f43282fdaaa77e814df2f952235/core/native/src/internal/Platform.kt#L19) (more or less)
```kotlin
Instant(tm.tv_sec.convert(), tm.tv_nsec.convert())
```

**Comment by JakeWharton** [comment]
Good catch. This file was copied from Molecule, so it's a problem there, too. Maybe also in Redwood since I've copied it there as well haha.
