### ISSUE TITLE
Border Modifier

### ISSUE THREAD

**Issue by opatry** [JakeWharton/mosaic#50]
Being able to draw borders around layouts would be great.
I guess `Modifier.border(BorderStyle)` could be good enough?

Maybe  [JakeWharton/flip-tables](https://github.com/JakeWharton/flip-tables) could be used under the hood?

I imagine being able to draw single line borders, double line border, rounded corners, square corners (defined by `BorderStyle`?)
See https://en.wikipedia.org/wiki/Box-drawing_character#Box_Drawing

```
       | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | A | B | C | D | E | F
U+250x | ─ | ━ | │ | ┃ | ┄ | ┅ | ┆ | ┇ | ┈ | ┉ | ┊ | ┋ | ┌ | ┍ | ┎ | ┏
U+251x | ┐ | ┑ | ┒ | ┓ | └ | ┕ | ┖ | ┗ | ┘ | ┙ | ┚ | ┛ | ├ | ┝ | ┞ | ┟
U+252x | ┠ | ┡ | ┢ | ┣ | ┤ | ┥ | ┦ | ┧ | ┨ | ┩ | ┪ | ┫ | ┬ | ┭ | ┮ | ┯
U+253x | ┰ | ┱ | ┲ | ┳ | ┴ | ┵ | ┶ | ┷ | ┸ | ┹ | ┺ | ┻ | ┼ | ┽ | ┾ | ┿
U+254x | ╀ | ╁ | ╂ | ╃ | ╄ | ╅ | ╆ | ╇ | ╈ | ╉ | ╊ | ╋ | ╌ | ╍ | ╎ | ╏
U+255x | ═ | ║ | ╒ | ╓ | ╔ | ╕ | ╖ | ╗ | ╘ | ╙ | ╚ | ╛ | ╜ | ╝ | ╞ | ╟
U+256x | ╠ | ╡ | ╢ | ╣ | ╤ | ╥ | ╦ | ╧ | ╨ | ╩ | ╪ | ╫ | ╬ | ╭ | ╮ | ╯
U+257x | ╰ | ╱ | ╲ | ╳ | ╴ | ╵ | ╶ | ╷ | ╸ | ╹ | ╺ | ╻ | ╼ | ╽ | ╾ | ╿
```

In terminal app, it's always painful to achieve this:
- border length depending on content or requested width
- support minWidth + dynamic width
- pad end of each lines to draw right border

Would be a nice addition to
- #11 
- #8 
- #7

**Comment by JakeWharton** [comment]
Going to tracking everything with #8 since we currently have nothing. Once we have modifiers we can split out issues for anything that doesn't make the first cut.
