### ISSUE TITLE
Render as fast as possible

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/mosaic#507]
Right now we render every 50ms, but in reality we need to go as fast as possible. We can send frames endlessly, but they should do minimal work unless something has changed. And they absolutely shouldn't re-render _unless_ something has changed.

**Comment by EpicDima** [comment]
Maybe we can change `delay(50L)` to `yield` in the loop in `mosaic.kt`?

It might also be useful to create a benchmark module to track performance with different changes

**Comment by JakeWharton** [comment]
Yeah, great idea.

**Comment by JakeWharton** [comment]
I recently updated [Redwood](https://github.com/cashapp/redwood) rendering and have two observations:
- The applier start/end change callbacks are a good indicator of changes that need rendered, but cannot be relied upon for _when_ to render. This is because things like `movableContentOf` will actually perform two passes over the node tree and produce two start/end callback pairs.
- Rendering should occur at the end of a frame by the thing which sends the frame. There is no first frame, however, and so at the end of `setContent` there needs to be a render.
