### ISSUE TITLE
Hero animation renders incorrectly as SVG

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/mosaic#6]
Loses a leading space somehow.

Filed https://github.com/marionebl/svg-term/issues/19

**Comment by gowthamgts** [comment]
also, it doesn't work on github mobile. seeing only one frame.

**Comment by BigBadaboom** [comment]
> This SVG has a slight rendering bug

*Just in case you haven't already figured this out...*

The SVG is rendering correctly. The rectangle is at X=0 and so is the text.  So it must be a SVG generation bug.

**Comment by JakeWharton** [comment]
Right. The problem is the conversion to SVG from the asciinema format and not the rendering of the SVG by a browser.
