### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by TWiStErRob** [JakeWharton/mosaic#80]
I was playing around and I was having problems making it work out of the box, but I did it in the end. I'm opening an issue instead of a PR, because I'm not sure in what style would you apply these changes. The main fix that's absolutely necessary is patch 2 for `jansi` (see 4.).

Below is what I observed and learned:
 1. IntelliJ IDEA terminal view supports color and relocation of cursor  
   (Gradle output is colored and workers are shown)
    * Command Prompt (cmd)
    * Windows Powershell
    * Ubuntu Bash (from WSL)
    * ![image](https://user-images.githubusercontent.com/2906988/200530262-08dbbda6-92c9-49f9-9cd9-bc7022b66bd6.png)
 2. Gradle `:run` task is `JavaExec` type and it messes with System.out in some way  
   See https://github.com/spring-projects/spring-boot/issues/24169 where they gave up supporting colors in Gradle, this seems to be because of https://github.com/gradle/gradle/issues/1251, but this assumption is not conclusive as they're talking about console input there.
 3. `:jar` in `samples` doesn't produce a runnable jar file even though the `application` plugin is applied. (easy fix)
 
	<details><summary>Patch 1: make jar runnable</summary>
	
	Applied to each sample:
	```gradle
	jar {
		manifest {
			attributes(
				'Main-Class': mainClassName,
			)
		}
		from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }}
		exclude('META-INF/versions/9/module-info.class')
	}
	```
	
	</details>

 4. `jansi` is not set up correctly in mosaic, because it detects tty, but is not rendering correctly

	<details><summary>Example unprocessed ansi output</summary>
	
	```
	Tests: 10 total←[K
	Time:  0s      ←[K
	←[F←[F←[30;43m RUNS ←[39;49m tests/←[1mlogin.kt←[22m                   ←[K
	←[30;43m RUNS ←[39;49m tests/←[1msignup.kt←[22m                  ←[K
	←[30;43m RUNS ←[39;49m tests/←[1mforgot-password.kt←[22m         ←[K
	←[30;43m RUNS ←[39;49m tests/←[1mreset-password.kt←[22m          ←[K
	                                        ←[K
	Tests: ←[33m4 running←[39m, 10 total              ←[K
	Time:  0s                               ←[K
	←[43m                ←[100m                        ←[0m←[K
	←[F←[F←[F←[F←[F←[F←[F←[F←[30;43m RUNS ←[39;49m tests/←[1mlogin.kt←[22m                   ←[K
	←[30;43m RUNS ←[39;49m tests/←[1msignup.kt←[22m                  ←[K
	←[30;43m RUNS ←[39;49m tests/←[1mforgot-password.kt←[22m         ←[K
	←[30;43m RUNS ←[39;49m tests/←[1mreset-password.kt←[22m          ←[K
	                                        ←[K
	Tests: ←[33m4 running←[39m, 10 total              ←[K
	Time:  0s                               ←[K
	←[100m                                        ←[0m←[K
	←[F←[F←[F←[F←[F←[F←[F←[F←[30;43m RUNS ←[39;49m tests/←[1mlogin.kt←[22m                   ←[K
	←[30;43m RUNS ←[39;49m tests/←[1msignup.kt←[22m                  ←[K
	←[30;43m RUNS ←[39;49m tests/←[1mforgot-password.kt←[22m         ←[K
	←[30;43m RUNS ←[39;49m tests/←[1mreset-password.kt←[22m          ←[K
	                                        ←[K
	```
	
	</details>
	
	<details><summary>Patch 2: set up jansi as <a href="https://github.com/fusesource/jansi#example-usage">documented</a></summary>
	
	```patch
	diff --git a/mosaic-runtime/src/main/kotlin/com/jakewharton/mosaic/output.kt b/mosaic-runtime/src/main/kotlin/com/jakewharton/mosaic/output.kt
	--- a/mosaic-runtime/src/main/kotlin/com/jakewharton/mosaic/output.kt	(revision 95c0826ab30a226e363ee773904fb2e7b3bb6d01)
	+++ b/mosaic-runtime/src/main/kotlin/com/jakewharton/mosaic/output.kt	(date 1667899762778)
	@@ -36,6 +36,10 @@
	 internal object AnsiOutput : Output {
	    private var lastHeight = 0
	 
	+	init {
	+		AnsiConsole.systemInstall()
	+	}
	+
	    override fun display(canvas: TextCanvas) {
	        val rendered = buildString {
	            repeat(lastHeight) {
	```
	
	</details>
 5. At this point running `gradlew -p samples :jest:jar` and then `java -jar samples\jest\build\libs\jest.jar` works nicely (ignoring Unicode problems)
    * ![image](https://user-images.githubusercontent.com/2906988/200529287-a009a5e5-b877-4fc6-82fd-d86b5e406c07.png)
    * ![image](https://user-images.githubusercontent.com/2906988/200529534-28874e83-05e8-488b-bf8c-2bb63cf10593.png)

**Comment by JakeWharton** [comment]
Is this still an issue? I don't have a Windows machine to test.

1 & 2 don't seem relevant to our code. We don't do terminal detection and unconditionally emit ANSI control sequences today.

3 is not a goal. Use the `installDist` or `distZip` tasks to produce a runnable binary (either as an exploded folder or a .zip)

If 4 is still an issue, you can send a PR to `platform.kt` and run install before assigning the `out` private property.

**Comment by TWiStErRob** [comment]
Will have a look again.

**Comment by TWiStErRob** [comment]
1. was just context to see where I'm coming from
2. and what I tried.
3. Ugh, [RTFM](https://github.com/JakeWharton/mosaic#samples), :slap:, thanks!
4. Yes, still an issue &rarr; https://github.com/JakeWharton/mosaic/pull/249
5. The right command is indeed `gradlew :samples:jest:installDist && samples\jest\build\install\jest\bin\jest.bat`
