### ISSUE TITLE
Robot sample problem on Windows

### ISSUE THREAD

**Issue by NorbertSandor** [JakeWharton/mosaic#97]
I have built the latest version from repository and running the robot sample in a command prompt on Windows 11 results in the following output:

```
D:\Project\mosaic\samples\robot\build\distributions\robot-0.4.0-SNAPSHOT\robot-0.4.0-SNAPSHOT\bin>robot.bat
Use arrow keys to move the face. Press ΓÇ£qΓÇ¥ to exit.
Position: 0, 0   World: 20, 10

^_^
```

Nothing happens when I press the arrow keys, `q` works for quit.

**Comment by JakeWharton** [comment]
Yeah unfortunately Windows doesn't work too well. See also #80. Hopefully I can improve support over time.

**Comment by TWiStErRob** [comment]
Raised PR: https://github.com/JakeWharton/mosaic/pull/250
Windows has a different raw stream of bytes for the "arrow key" escape sequence.
